FROM centos

ARG GLUE_VERSION=3.0
ARG GLUE_REPO=aws-glue-libs
ARG SPARK_NAME=spark-3.1.1-amzn-0-bin-3.2.1-amzn-3

ENV MAVEN=https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-common/apache-maven-3.6.0-bin.tar.gz
ENV SPARK=https://aws-glue-etl-artifacts.s3.amazonaws.com/glue-3.0/${SPARK_NAME}.tgz
ENV GLUE=https://github.com/awslabs/${GLUE_REPO}.git

RUN mkdir glue
RUN yum install -y python3 java-1.8.0-openjdk java-1.8.0-openjdk-devel tar git wget zip
RUN ln -s /usr/bin/python3 /usr/bin/python && ln -s /usr/bin/pip3 /usr/bin/pip
# todo: does pandas always come in glue?
RUN pip install pandas boto3 pynt

# todo: test glue version
WORKDIR ./glue

RUN git clone $GLUE && cd ${GLUE_REPO} && git checkout v${GLUE_VERSION} && cd ..

RUN wget $SPARK
RUN wget $MAVEN
RUN tar zxfv apache-maven-3.6.0-bin.tar.gz
RUN tar zxfv ${SPARK_NAME}.tgz
RUN rm ${SPARK_NAME}.tgz
RUN rm apache-maven-3.6.0-bin.tar.gz
RUN mv $(rpm -q -l java-1.8.0-openjdk-devel | grep "/bin$" | rev | cut -d"/" -f2- |rev) /usr/lib/jvm/jdk

ENV SPARK_HOME /glue/${SPARK_NAME}
ENV MAVEN_HOME /glue/apache-maven-3.6.0
ENV JAVA_HOME /usr/lib/jvm/jdk
ENV GLUE_HOME /glue/aws-glue-libs
ENV PATH $PATH:$MAVEN_HOME/bin:$SPARK_HOME/bin:$JAVA_HOME/bin:$GLUE_HOME/bin
RUN sh /glue/aws-glue-libs/bin/glue-setup.sh
RUN sed -i '/mvn -f/a rm /glue/aws-glue-libs/jarsv1/netty-*' /glue/aws-glue-libs/bin/glue-setup.sh
RUN sed -i '/mvn -f/a rm /glue/aws-glue-libs/jarsv1/javax.servlet-3.*' /glue/aws-glue-libs/bin/glue-setup.sh
RUN yum clean all
RUN rm -rf /var/cache/yum

CMD ["bash"]
